### ISSUE TITLE
执行build.gradle报错

### ISSUE THREAD

**Issue by augetyMax** [WeBankBlockchain/WeIdentity-Build-Tools#228]
Build file '/home/augety/tools/WeIdentity-Build-Tools/build.gradle' line: 266

Could not compile build file '/home/augety/tools/WeIdentity-Build-Tools/build.gradle'.
> startup failed:
  build file '/home/augety/tools/WeIdentity-Build-Tools/build.gradle': 266: unable to resolve class MavenDeployment 
   @ line 266, column 30.
                 beforeDeployment { MavenDeployment deployment -> signing.signPom(deployment) }
                                  ^
环境：

------------------------------------------------------------
Gradle 6.9.3
------------------------------------------------------------

Build time:   2022-10-17 07:44:02 UTC
Revision:     a6198e44749b18b37e26b3b3467db17e034bcff4

Kotlin:       1.4.20
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.17 (Ubuntu 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OS:           Linux 5.15.0-60-generic amd64

**Comment by augetyMax** [comment]
另外，这个项目部署的顺序是怎么样的，新手搞了一天了还没部署上。。。

**Comment by youwenbusi** [comment]
gradle版本太高了，用6.5试试。部署顺序参考weid的文档https://weidentity.readthedocs.io/zh_CN/latest/docs/weidentity-installation-by-web.html
