### ISSUE TITLE
命令行方式不支持FISCO BCOS 3.0以上版本

### ISSUE THREAD

**Issue by tonyhth** [WeBankBlockchain/WeIdentity-Build-Tools#232]
运行compile.sh，报不支持3.x
Begin to check jdk...
jdk check finished.
begin to compile build tools...
currently FISCO BCOS 3.x is not supported.
compile finished.
begin to clean config...
clean finished...

**Comment by youwenbusi** [comment]
将在下个版本3.1.1支持
