### ISSUE TITLE
WeIdentity JAVA SDK 便捷使用工具-the weid does not exist on blockchain

### ISSUE THREAD

**Issue by g-chang** [WeBankBlockchain/WeIdentity-Build-Tools#81]
操作
./register_specific_issuer.sh --type college --weid did:weid:1:0x0ed46c044f3f60aea9ac10478295979a78726929
错误
[RegisterIssuer] Add FAILED: the weid does not exist on blockchain
根源-register_specific_issuer.sh
private_key=${SOURCE_CODE_DIR}/output/admin/ecdsa_key

尝试更改-此种配置才能正确执行
private_key=${SOURCE_CODE_DIR}/output/create_weid/0x0ed46c044f3f60aea9ac10478295979a78726929/ecdsa_key

**Comment by chaoxinhu** [comment]
@g-chang 亲，其实那个脚本中的语句是将链的部署者添加为Specific Issuer的。感谢报告，我们在下一个版本的文档里修改一下。
