### ISSUE TITLE
NotoSansCJKtc-Regular.ttf  文件不存在

### ISSUE THREAD

**Issue by yangjianyao** [WeBankBlockchain/WeIdentity-Build-Tools#94]
Build file '/data/WeIdentity/weid-build-tools-1.0.8/build.gradle' line: 132
java.io.FileNotFoundException: https://github.com/WeBankFinTech/WeIdentity/raw/master/context/NotoSansCJKtc-Regular.ttf

这个文件不存在，编译运行报错

**Comment by junqizhang-dev** [comment]
目前已经在初始安装的时候，不需要这个文件了。
